version: '3'
services:
  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'home-credit'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'home-credit'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./mount/mysql:/var/lib/mysql
