version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8811:8811
    environment:
      MYSQL_HOST: mysqldb